# Generated by Django 5.0.3 on 2024-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
    ]
